const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {JSDOM} = require('jsdom');

const root = path.resolve(__dirname, '..');
const dom = new JSDOM(fs.readFileSync(path.join(root, 'index.html'), 'utf8'), {
  url: 'https://stepkobetsu-hub.github.io/invoice-pdf/',
  runScripts: 'outside-only'
});
const {window} = dom;
window.localStorage.setItem('stepStaffAppAuth', JSON.stringify({systemPortalSessionToken:'test-session'}));
window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
window.HTMLDialogElement.prototype.close=function(){this.open=false;};
window.HTMLFormElement.prototype.submit=function(){
  const value=name=>this.querySelector(`[name="${name}"]`)?.value||'';
  const action=value('action'),requestId=value('requestId'),bridgeNonce=value('bridgeNonce');
  const invoices=[
    {invoiceNumber:'202608102',partnerName:'最新の取引先',honorific:'様',subject:'2026年9月分',invoiceDate:'2026/08/10',dueDate:'2026/08/31',createdAt:'2026/08/10',updatedAt:'2026/08/10 12:30:00',memo:'中2',tags:'神領',paymentStatus:'未入金',subtotal:10000,tax:1000,total:11000,email:'new@example.com',cc:'',postal:'487-0024',prefecture:'愛知県',address1:'春日井市大留町1丁目23-2',address2:'',details:[{name:'夏期講習',unitPrice:10000,quantity:1,amount:10000,taxRate:'10%'}],pdfStatus:'PDF作成済み',sendStatus:'未送信',dlStatus:'未取得',warnings:[]},
    {invoiceNumber:'202608101',partnerName:'以前の取引先',honorific:'様',subject:'2026年8月分',invoiceDate:'2026/08/09',dueDate:'2026/08/30',createdAt:'2026/08/09',updatedAt:'2026/08/09 11:00:00',memo:'中1',tags:'大手',paymentStatus:'入金済',paymentDate:'2026/08/10',paymentAmount:9900,paymentMemo:'振込手数料差引',subtotal:9000,tax:900,total:9900,email:'old@example.com',cc:'',postal:'487-0024',prefecture:'愛知県',address1:'春日井市大留町1丁目23-2',address2:'',details:[{name:'授業料',unitPrice:9000,quantity:1,amount:9000,taxRate:'10%'}],pdfStatus:'PDF作成済み',sendStatus:'送信済み',dlStatus:'未アクセス',warnings:[]}
  ];
  const data=action==='getDashboard'?{user:'テスト担当者',invoices,history:[{timestamp:'2026/08/10 10:00:00',action:'請求書作成',invoiceNumber:'202608102',sendStatus:'未送信',urlStatus:'',result:'正常'}]}:{ok:true};
  window.setTimeout(()=>window.dispatchEvent(new window.MessageEvent('message',{origin:'https://script.google.com',data:{requestId,bridgeNonce,result:{ok:true,data}}})),0);
};
window.print=()=>{};
window.confirm=()=>true;
window.fetch=async(url,options={})=>{
  if(String(url).includes('step-invoice-api.stepkobetsu.workers.dev')){
    if(String(url).endsWith('/api/app/dashboard'))return {ok:false,json:async()=>({ok:false,error:'D1 test fallback'})};
    if(options.method==='POST'&&String(url).includes('/payment')){const number=decodeURIComponent(String(url).split('/').at(-2));const source=invoices.find(item=>item.invoiceNumber===number);return {ok:true,json:async()=>({ok:true,data:{invoice:{...source,...JSON.parse(options.body)}}})};}
    if(options.method==='DELETE')return {ok:true,json:async()=>({ok:true,data:{deleted:1}})};
    if(options.method==='POST'){const invoice=JSON.parse(options.body).invoice;return {ok:true,json:async()=>({ok:true,data:{invoice}})};}
  }
  return {ok:true,json:async()=>({results:[]})};
};
window.eval(fs.readFileSync(path.join(root,'assets/core.js'),'utf8'));
window.eval(fs.readFileSync(path.join(root,'assets/invoice-pdf.js'),'utf8'));
window.eval(fs.readFileSync(path.join(root,'assets/receipt-pdf.js'),'utf8'));
window.eval(fs.readFileSync(path.join(root,'assets/app.js'),'utf8'));
window.eval(fs.readFileSync(path.join(root,'assets/receipts.js'),'utf8'));

(async()=>{
  await new Promise(resolve=>window.setTimeout(resolve,150));
  const document=window.document;
  assert.equal(document.querySelector('#view-invoices').classList.contains('active'),true);
  assert.equal(document.querySelectorAll('.app-shell > .sidebar').length,1);
  assert.equal(document.querySelectorAll('#invoiceList .invoice-list-item').length,2);
  assert.match(document.querySelector('#invoiceList .invoice-list-item').textContent,/最新の取引先/);
  assert.equal(document.querySelector('#invoiceList .invoice-list-item').classList.contains('active'),true);
  assert.match(document.querySelector('#invoiceDetailPanel').textContent,/最新の取引先/);
  assert.match(document.querySelector('.invoice-detail-column').textContent,/デモ送信/);
  assert.equal(document.body.textContent.includes('テスト送信モード'),false);
  assert.equal(document.querySelector('[name="testRecipient"]'),null);
  assert.match(document.querySelector('.invoice-detail-column').textContent,/CSV一括追加/);
  assert.match(document.querySelector('.invoice-detail-column').textContent,/請求書を作成/);
  assert.match(document.querySelector('#invoiceDetailPanel').textContent,/編集/);
  assert.match(document.querySelector('#invoiceDetailPanel').textContent,/複製／変換/);
  assert.match(document.querySelector('#invoiceDetailPanel').textContent,/請求書を複製/);
  assert.match(document.querySelector('#invoiceDetailPanel').textContent,/領収書/);
  assert.match(document.querySelector('#invoiceDetailPanel').textContent,/PDFをダウンロード/);
  assert.equal(document.querySelector('#selectedPaymentStatus summary').textContent,'未入金');
  assert.equal(document.querySelectorAll('[data-payment-value]').length,3);
  document.querySelector('[data-invoice-action="duplicate_invoice"]').click();
  assert.equal(document.querySelector('#documentEditorDialog').open,true);
  assert.match(document.querySelector('#documentEditorTitle').textContent,/請求書を複製/);
  assert.match(document.querySelector('#documentEditorPreview').textContent,/請求書/);
  assert.ok(document.querySelector('#documentPartnerSearch'));
  document.querySelector('#documentEditorDialog').close();
  document.querySelector('[data-invoice-action="convert_receipt"]').click();
  assert.equal(document.querySelector('#documentEditorDialog').open,true);
  assert.match(document.querySelector('#documentEditorTitle').textContent,/請求書から領収書を作成/);
  assert.match(document.querySelector('[name="documentNumber"]').value,/^\d{9}$/);
  assert.match(document.querySelector('[name="subject"]').value,/^2026年[89]月分$/);
  assert.match(document.querySelector('#documentEditorPreview').textContent,/領収書/);
  document.querySelector('#documentEditorDialog').close();
  Object.assign(window.StepInvoiceApp.state.partners.at(-1),{'学年':'中3','教室':'大手'});
  window.StepReceipts.openNewReceipt();
  document.querySelector('#documentPartnerCombo > button').click();
  document.querySelector('#documentPartnerResults [data-partner-code]:first-child').click();
  assert.equal(document.querySelector('#documentEditorForm [name="memo"]').value,'中3');
  assert.equal(document.querySelector('#documentEditorForm [name="tags"]').value,'大手');
  document.querySelector('#documentEditorDialog').close();
  window.StepReceipts.openDemoReceipt();
  assert.equal(document.querySelector('#documentEditorForm [name="subject"]').value,'テスト送信');
  assert.equal(document.querySelectorAll('#documentEditorDetails tr').length,2);
  document.querySelector('#documentEditorDialog').close();
  assert.ok(document.querySelector('#paymentDateDialog'));
  document.querySelector('[data-payment-value="入金済"]').click();
  assert.equal(document.querySelector('#paymentDateDialog').open,true);
  assert.equal(document.querySelector('#paymentAmountInput').value,'11000');
  assert.equal(document.querySelector('#paymentMemoInput').value,'');
  document.querySelector('#paymentAmountInput').value='10700';
  document.querySelector('#paymentAmountInput').dispatchEvent(new window.Event('input',{bubbles:true}));
  assert.equal(document.querySelector('#paymentMemoInput').value,'差額－300円');
  document.querySelector('#paymentAmountInput').value='11500';
  document.querySelector('#paymentAmountInput').dispatchEvent(new window.Event('input',{bubbles:true}));
  assert.equal(document.querySelector('#paymentMemoInput').value,'差額＋500円');
  document.querySelector('#paymentAmountInput').value='11000';
  document.querySelector('#paymentAmountInput').dispatchEvent(new window.Event('input',{bubbles:true}));
  assert.equal(document.querySelector('#paymentMemoInput').value,'');
  document.querySelector('#paymentDateDialog').close();
  document.querySelectorAll('#invoiceList .invoice-list-item')[1].click();
  assert.match(document.querySelector('#invoiceDetailPanel').textContent,/入金日：2026\/08\/10/);
  assert.match(document.querySelector('#invoiceDetailPanel').textContent,/入金金額：9,900円/);
  assert.match(document.querySelector('#invoiceDetailPanel').textContent,/入金メモ：振込手数料差引/);
  assert.equal(document.querySelector('[data-invoice-action="mail"]').textContent,'メール再送信');
  document.querySelectorAll('#invoiceList .invoice-list-item')[0].click();
  assert.ok(document.querySelector('[name="defaultBank"]'));
  assert.ok(document.querySelector('[name="defaultNote"]'));
  assert.ok(document.querySelector('.advanced-settings [name="apiUrl"]'));
  document.querySelector('[data-view="settings"]').click();
  assert.match(document.querySelector('#settingsDocumentHeading').textContent,/現在：請求書設定/);
  document.querySelector('#receiptSettingsTab').click();
  assert.match(document.querySelector('#settingsDocumentHeading').textContent,/現在：領収書設定/);
  assert.equal(document.querySelector('#receiptSettingsPanel').classList.contains('hidden'),false);
  assert.equal(document.querySelector('[name="receiptBusinessName"]').disabled,false);
  assert.equal(document.querySelector('[name="businessName"]').disabled,true);
  assert.equal(document.querySelector('#saveSettingsButton').textContent,'領収書設定を保存');
  document.querySelector('[data-view="invoices"]').click();
  assert.doesNotMatch(document.querySelector('#view-invoices').textContent,/新しい請求書から順に表示しています/);
  assert.deepEqual([...document.querySelectorAll('#invoiceDateField option')].map(option=>option.textContent),['作成日','請求日','最終更新日','お支払期限日']);
  const today=new Date(),expectedFrom=`${today.getFullYear()-1}-${String(today.getMonth()+1).padStart(2,'0')}-01`,periodEnd=new Date(today.getFullYear(),today.getMonth()+2,0),expectedTo=`${periodEnd.getFullYear()}-${String(periodEnd.getMonth()+1).padStart(2,'0')}-${String(periodEnd.getDate()).padStart(2,'0')}`;
  assert.equal(document.querySelector('#invoiceDateFrom').value,expectedFrom);
  assert.equal(document.querySelector('#invoiceDateTo').value,expectedTo);
  document.querySelector('#invoiceFreeSearch').value='夏期講習';
  document.querySelector('#invoiceFreeSearch').dispatchEvent(new window.Event('input',{bubbles:true}));
  assert.equal(document.querySelectorAll('#invoiceList .invoice-list-item').length,1);
  assert.match(document.querySelector('#invoiceList').textContent,/最新の取引先/);
  document.querySelector('#clearInvoiceSearch').click();
  assert.equal(document.querySelector('#invoiceFreeSearch').value,'');
  assert.equal(document.querySelector('#invoiceDateFrom').value,expectedFrom);
  assert.equal(document.querySelector('#invoiceDateTo').value,expectedTo);
  document.querySelector('#invoiceDateField').value='invoiceDate';
  document.querySelector('#invoiceDateFrom').value='2026-08-09';
  document.querySelector('#invoiceDateTo').value='2026-08-09';
  document.querySelector('#invoiceDateTo').dispatchEvent(new window.Event('change',{bubbles:true}));
  assert.equal(document.querySelectorAll('#invoiceList .invoice-list-item').length,1);
  assert.match(document.querySelector('#invoiceList').textContent,/以前の取引先/);
  document.querySelector('#clearInvoiceSearch').click();
  assert.equal(document.querySelector('#invoiceDateFrom').value,'2026-08-09');
  assert.equal(document.querySelector('#invoiceDateTo').value,'2026-08-09');
  document.querySelector('#invoiceDateField').value='createdAt';
  document.querySelector('#invoiceDateFrom').value=expectedFrom;
  document.querySelector('#invoiceDateTo').value=expectedTo;
  document.querySelector('#invoiceDateTo').dispatchEvent(new window.Event('change',{bubbles:true}));
  const manualUnitPrice=document.querySelector('[name="detailUnitPrice"]');manualUnitPrice.value='-10000';assert.equal(manualUnitPrice.checkValidity(),true);
  document.querySelector('[data-invoice-action="edit"]').click();
  const editUnitPrice=document.querySelector('[name="editDetailUnitPrice"]');editUnitPrice.value='-10000';assert.equal(editUnitPrice.checkValidity(),true);
  document.querySelector('#editInvoiceDialog').close();
  document.querySelector('#invoiceList .invoice-list-item').click();
  document.querySelector('[data-invoice-tab="history"]').click();
  assert.match(document.querySelector('#invoiceDetailPanel').textContent,/請求書作成/);
  document.querySelector('[data-invoice-action="mail"]').click();
  assert.equal(document.querySelector('#invoiceMailDialog').open,true);
  assert.match(document.querySelector('#invoiceMailDialog').textContent,/請求書メールの確認/);
  const worker=fs.readFileSync(path.join(root,'cloudflare/src/index.js'),'utf8');
  const backend=fs.readFileSync(path.join(root,'apps-script/Code.gs'),'utf8');
  assert.match(backend,/入金金額/);
  assert.match(backend,/paymentAmount/);
  assert.match(backend,/入金メモ/);
  assert.match(backend,/paymentMemo/);
  assert.match(worker,/ご請求金額/);
  assert.match(worker,/const isReceipt=documentType==="receipt",label=isReceipt\?"領収書":"請求書"/);
  assert.match(worker,/お支払期限<\/dt>/);
  assert.match(worker,/ダウンロード期限：/);
  assert.doesNotMatch(worker,/請求日<\/dt>/);
  document.querySelector('#invoiceMailDialog').close();
  document.querySelector('#createDemoInvoiceFromList').click();
  await new Promise(resolve=>window.setTimeout(resolve,50));
  assert.equal(document.querySelector('#view-create').classList.contains('active'),true);
  assert.equal(document.querySelector('#createSinglePane').classList.contains('active'),true);
  assert.equal(document.querySelector('#singleInvoiceForm').elements.subject.value,'テスト送信');
  const demoRows=document.querySelectorAll('#singleDetailBody tr');
  assert.equal(demoRows.length,2);
  assert.equal(demoRows[0].querySelector('[name="detailName"]').value,'テスト');
  assert.equal(demoRows[0].querySelector('[name="detailUnitPrice"]').value,'100');
  assert.equal(demoRows[1].querySelector('[name="detailName"]').value,'テスト割引');
  assert.equal(demoRows[1].querySelector('[name="detailUnitPrice"]').value,'-100');
  const demoInvoiceDate=document.querySelector('#singleInvoiceForm').elements.invoiceDate.value;
  const demoDueDate=document.querySelector('#singleInvoiceForm').elements.dueDate.value;
  assert.equal((new Date(`${demoDueDate}T00:00:00`)-new Date(`${demoInvoiceDate}T00:00:00`))/86400000,21);
  assert.match(document.querySelector('#singleInvoiceLivePreview').textContent,/テスト送信/);
  assert.match(document.querySelector('#singleInvoiceLivePreview').textContent,/テスト割引/);
  console.log('invoice workspace tests passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
