const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {JSDOM} = require('jsdom');

const root = path.resolve(__dirname, '..');
const dom = new JSDOM(fs.readFileSync(path.join(root, 'index.html'), 'utf8'), {
  url: 'https://stepkobetsu-hub.github.io/invoice-pdf/#partners',
  runScripts: 'outside-only'
});
const {window} = dom;
window.localStorage.setItem('stepStaffAppAuth',JSON.stringify({systemPortalSessionToken:'test-staff-session'}));
let submittedStaffToken='';
window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
window.HTMLDialogElement.prototype.close=function(){this.open=false;};
window.HTMLFormElement.prototype.submit=function(){
  const value=name=>this.querySelector(`[name="${name}"]`)?.value||'';
  const requestId=value('requestId'),bridgeNonce=value('bridgeNonce'),action=value('action');
  submittedStaffToken=value('systemPortalSessionToken');
  if(!requestId)return;
  const data=action==='getDashboard'?{invoices:[],history:[]}:action==='getSupportData'?{partners:window.StepInvoiceCore.DEMO_PARTNERS}:{count:1};
  window.setTimeout(()=>window.dispatchEvent(new window.MessageEvent('message',{origin:'https://script.google.com',data:{requestId,bridgeNonce,result:{ok:true,data}}})),0);
};
window.print=()=>{};
window.fetch=async(url,options={})=>{
  if(String(url).includes('step-invoice-api.stepkobetsu.workers.dev')){
    submittedStaffToken=String(options.headers?.Authorization||'').replace(/^Bearer\s+/,'');
    if(String(url).endsWith('/api/app/apps-script')){
      const request=JSON.parse(options.body),data=request.action==='getDashboard'?{invoices:[],history:[]}:request.action==='getSupportData'?{partners:window.StepInvoiceCore.DEMO_PARTNERS}:{count:1};
      return {ok:true,json:async()=>({ok:true,data})};
    }
    if(String(url).endsWith('/api/app/dashboard'))return {ok:true,json:async()=>({ok:true,data:{invoices:[],history:[],user:'テスト担当者'}})};
    if(String(url).endsWith('/api/app/invoices')){const invoice=JSON.parse(options.body).invoice;return {ok:true,json:async()=>({ok:true,data:{invoice:{...invoice,details:invoice.details||[],sendStatus:'未送信',dlStatus:'未取得',pdfStatus:'未作成',warnings:[]}}})};}
  }
  return {ok:true,json:async()=>({status:200,results:[{address1:'愛知県',address2:'春日井市',address3:'大留町'}]})};
};
window.eval(fs.readFileSync(path.join(root, 'assets/core.js'), 'utf8'));
window.eval(fs.readFileSync(path.join(root, 'assets/invoice-pdf.js'), 'utf8'));
window.eval(fs.readFileSync(path.join(root, 'assets/app.js'), 'utf8'));

async function main(){
  const document=window.document;
  assert.equal(document.querySelector('#view-invoices').classList.contains('active'),true);
  assert.equal(window.location.hash,'#invoices');
  assert.equal(window.StepInvoiceApp.initialViewForNavigation('navigate','#settings'),'invoices');
  assert.equal(window.StepInvoiceApp.initialViewForNavigation('reload','#settings'),'settings');
  assert.equal(window.StepInvoiceApp.initialViewForNavigation('back_forward','#receipts'),'receipts');
  document.querySelector('[data-view="create"]').click();
  assert.equal(window.location.hash,'#create');
  document.querySelector('[data-create-method="single"]').click();
  await new Promise(resolve=>window.setTimeout(resolve,0));
  assert.equal(submittedStaffToken,'test-staff-session');
  assert.equal(document.querySelector('#createSinglePane').classList.contains('active'),true);
  assert.ok(document.querySelector('.single-invoice-editor-layout'));
  assert.ok(document.querySelector('.single-invoice-editor-fields'));
  assert.ok(document.querySelector('.single-invoice-live-preview'));
  assert.ok(document.querySelector('#singleInvoiceLivePreview .invoice-page'));
  assert.match(document.querySelector('#singleInvoiceLivePreview').textContent,/取引先未選択/);
  assert.match(document.querySelector('[name="invoiceNumber"]').value,/^\d{9}$/);
  assert.equal(document.querySelector('[name="invoiceNumber"]').readOnly,false);
  const invoiceDate=document.querySelector('[name="invoiceDate"]').value;
  const dueDate=document.querySelector('[name="dueDate"]').value;
  assert.equal((new Date(`${dueDate}T00:00:00`)-new Date(`${invoiceDate}T00:00:00`))/86400000,21);
  document.querySelector('#saveSingleInvoice').click();
  assert.equal(document.querySelector('#previewDialog').open,false);
  assert.match(document.querySelector('#globalAlert').textContent,/取引先/);
  assert.match(document.querySelector('#globalAlert').textContent,/明細1の品目/);
  assert.match(document.querySelector('#globalAlert').textContent,/明細1の単価/);
  assert.equal(document.querySelector('#singlePartner').classList.contains('field-missing'),true);
  assert.match(document.querySelector('#singleSaveStatus').textContent,/入力が必要な項目/);
  assert.equal(document.querySelector('#singleSaveStatus').classList.contains('error'),true);
  const saveButton=document.querySelector('#singleInvoiceForm button[type="submit"]');
  assert.equal(saveButton.textContent,'保存');
  assert.equal(document.querySelector('#singleInvoiceForm').noValidate,true);
  assert.equal(saveButton.id,'saveSingleInvoice');
  assert.ok(document.querySelector('#singleInvoiceLivePreview .invoice-page'));
  assert.equal(document.querySelector('#confirmPdf'),null);

  const firstDetailName=document.querySelector('[name="detailName"]');
  assert.equal(firstDetailName.getAttribute('inputmode'),'text');
  assert.equal(firstDetailName.getAttribute('lang'),'ja');
  document.querySelector('#addSingleDetail').click();
  await new Promise(resolve=>window.setTimeout(resolve,0));
  const detailRows=document.querySelectorAll('#singleDetailBody tr');
  const addedDetail=detailRows[detailRows.length-1];
  assert.equal(document.activeElement,addedDetail.querySelector('[name="detailName"]'));
  assert.equal(addedDetail.querySelector('[name="detailName"]').getAttribute('inputmode'),'text');
  const addedPrice=addedDetail.querySelector('[name="detailUnitPrice"]');
  addedPrice.value='－１０，０００';
  addedPrice.dispatchEvent(new window.Event('input',{bubbles:true}));
  assert.equal(addedPrice.value,'-10000');
  assert.match(window.localStorage.getItem('stepInvoiceSingleDraft'),/-10000/);
  addedDetail.querySelector('.remove-detail').click();

  await new Promise(resolve=>window.setTimeout(resolve,0));
  assert.equal(document.querySelectorAll('#partnerTable tbody tr').length,4);
  document.querySelector('#singlePartnerCombo > button').click();
  assert.equal(document.querySelectorAll('#singlePartnerResults [data-partner-code]').length,4);
  assert.match(document.querySelector('#singlePartnerResults [data-partner-code]:first-child').textContent,/ダミー取引先4/);
  assert.match(document.querySelector('#partnerTable').textContent,/mintcocoajasmine@gmail\.com/);
  assert.match(document.querySelector('#partnerTable').textContent,/kk8989892000@yahoo\.co\.jp/);
  assert.match(document.querySelector('#partnerTable').textContent,/skase\.days@gmail\.com/);
  assert.match(document.querySelector('#partnerTable').textContent,/chloeandnina1@gmail\.com/);

  const form=document.querySelector('#singleInvoiceForm');
  form.elements.partnerCode.value='DEMO001';
  form.elements.invoiceNumber.value='202608501';
  form.elements.subject.value='2026年8月分';
  form.elements.invoiceDate.value='2026-08-09';
  form.elements.dueDate.value='2026-08-31';
  document.querySelector('[name="detailName"]').value='授業料';
  document.querySelector('[name="detailUnitPrice"]').value='25000';
  document.querySelector('[name="detailQuantity"]').value='1';
  document.querySelector('[name="detailUnitPrice"]').dispatchEvent(new window.Event('input',{bubbles:true}));
  assert.equal(document.querySelector('#singleTotal').textContent,'27,500円');
  assert.match(document.querySelector('#singleInvoiceLivePreview').textContent,/ダミー取引先1/);
  assert.match(document.querySelector('#singleInvoiceLivePreview').textContent,/202608501/);
  assert.match(document.querySelector('#singleInvoiceLivePreview').textContent,/27,500/);
  assert.match(document.querySelector('#singleInvoicePreviewPage').getAttribute('style'),/--detail-count:1/);
  const twoLineHtml=window.StepInvoicePdf.pageHtml({...window.StepInvoiceCore.buildManualInvoice({invoiceNumber:'202608999',subject:'2026年8月分',invoiceDate:'2026-08-09',dueDate:'2026-08-30'},[{name:'授業料',unitPrice:25000,quantity:1,taxRate:10},{name:'分譲経費',unitPrice:2500,quantity:1,taxRate:10}],window.StepInvoiceCore.DEMO_PARTNERS[0])});
  assert.match(twoLineHtml,/--detail-count:2/);
  assert.match(twoLineHtml,/愛知県春日井市大留町1丁目23-2/);
  assert.doesNotMatch(twoLineHtml,/preview-watermark/);
  assert.match(window.StepInvoicePdf.pageHtml(window.StepInvoiceCore.buildManualInvoice({invoiceNumber:'202608998',subject:'2026年8月分',invoiceDate:'2026-08-09',dueDate:'2026-08-30'},[{name:'授業料',unitPrice:7000,quantity:1,taxRate:10}],window.StepInvoiceCore.DEMO_PARTNERS[0]),{preview:true}),/preview-watermark/);
  form.dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));
  await new Promise(resolve=>window.setTimeout(resolve,20));
  assert.match(document.querySelector('#invoiceList').textContent,/202608501/);
  assert.match(document.querySelector('#invoiceList').textContent,/ダミー取引先1/);

  document.querySelector('#openPartnerForm').click();
  const partnerForm=document.querySelector('#partnerForm');
  partnerForm.elements.customerCode.value='NEW001';
  partnerForm.elements.name.value='個別入力テスト';
  partnerForm.elements.email.value='new@example.com';
  partnerForm.elements.grade.value='中2';
  partnerForm.elements.campus.value='神領';
  partnerForm.dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));
  assert.match(document.querySelector('#partnerTable').textContent,/個別入力テスト/);
  document.querySelector('#singlePartnerSearch').value='NEW001';
  document.querySelector('#singlePartnerSearch').dispatchEvent(new window.Event('input',{bubbles:true}));
  assert.match(document.querySelector('#singlePartnerResults').textContent,/個別入力テスト/);
  document.querySelector('#singlePartnerResults [data-partner-code="NEW001"]').click();
  assert.equal(form.elements.memo.value,'中2');
  assert.equal(form.elements.tags.value,'神領');
  document.querySelector('[data-edit-partner="NEW001"]').click();
  assert.equal(document.querySelector('#partnerDialogTitle').textContent,'取引先を編集');
  assert.equal(partnerForm.elements.customerCode.readOnly,true);
  partnerForm.elements.name.value='個別入力テスト（編集済）';
  partnerForm.dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));
  assert.match(document.querySelector('#partnerTable').textContent,/個別入力テスト（編集済）/);
  assert.equal(document.querySelector('#partnerDialog #deletePartnerButton'),null);
  document.querySelector('[data-delete-partner="NEW001"]').click();
  assert.equal(document.querySelector('#deletePartnerDialog').open,true);
  assert.equal(document.querySelector('#confirmDeletePartner').disabled,true);
  document.querySelector('#deletePartnerCodeInput').value='NEW001';
  document.querySelector('#deletePartnerCodeInput').dispatchEvent(new window.Event('input',{bubbles:true}));
  document.querySelector('#deletePartnerCheck').checked=true;
  document.querySelector('#deletePartnerCheck').dispatchEvent(new window.Event('change',{bubbles:true}));
  assert.equal(document.querySelector('#confirmDeletePartner').disabled,false);
  document.querySelector('#confirmDeletePartner').click();
  await new Promise(resolve=>window.setTimeout(resolve,0));
  assert.doesNotMatch(document.querySelector('#partnerTable').textContent,/個別入力テスト（編集済）/);

  document.querySelector('#openPartnerForm').click();
  partnerForm.elements.postal.value='4870024';
  partnerForm.elements.postal.dispatchEvent(new window.Event('change',{bubbles:true}));
  await new Promise(resolve=>window.setTimeout(resolve,0));
  assert.equal(partnerForm.elements.postal.value,'487-0024');
  assert.equal(partnerForm.elements.prefecture.value,'愛知県');
  assert.equal(partnerForm.elements.address1.value,'春日井市大留町');
  document.querySelector('#partnerDialog').close();

  document.querySelector('#openStudentImport').click();
  assert.equal(document.querySelector('#studentImportDialog').open,true);
  assert.match(document.querySelector('#studentImportDialog').textContent,/生徒コード/);
  assert.match(document.querySelector('#studentImportDialog').textContent,/※半角英数で入力してください。/);
  assert.equal(document.querySelector('#studentSearchForm [name="studentCode"]').pattern,'[A-Za-z0-9]+');
  assert.match(document.querySelector('#settingsForm [name="apiUrl"]').value,/^https:\/\/script\.google\.com\/macros\/s\//);
  assert.equal(document.querySelector('#staffLoginLink').href,'https://stepkobetsu-hub.github.io/seiseki-kanri/');
  const backend=fs.readFileSync(path.join(root,'apps-script/Code.gs'),'utf8');
  const appSource=fs.readFileSync(path.join(root,'assets/app.js'),'utf8');
  assert.match(backend,/action:'verifySystemPortal'/);
  assert.match(backend,/AUTH_PERMISSION_LEVELS:\['2','3','4'\]/);
  assert.match(backend,/AUTH_PERMISSION_LEVELS\.includes\(String\(result\.permissionLevel\)\)/);
  assert.match(backend,/processPendingSends: \(\) => processPendingSends_\(requestAuth\)/);
  assert.match(backend,/prepared\.length===1\?buildBrevoSinglePayload_/);
  assert.match(backend,/function buildBrevoSinglePayload_\(/);
  assert.match(backend,/function ensureBrevoWebhook_\(/);
  assert.match(backend,/providerMessageId:providerId/);
  assert.match(backend,/email-opened/);
  assert.match(backend,/installQueueTrigger_\(\);\s*scheduleQueueRun_\(\);\s*return response/);
  assert.match(backend,/function scheduleQueueRun_\(\)/);
  assert.doesNotMatch(backend,/if\(payload\.preflight!==true\)processSendQueue\(\)/);
  assert.match(backend,/STEP_SPREADSHEET_CACHE_/);
  assert.match(backend,/replaceDetailRows_\(ds,/);
  assert.match(backend,/sheet\.deleteRows\(run\.start,run\.count\)/);
  assert.doesNotMatch(backend,/const rows=retained\.concat\(replacements\)/);
  assert.match(backend,/staff-auth:'\+hashToken_\(token\)/);
  assert.match(backend,/student-partner:' \+ code\.toLowerCase\(\)/);
  document.querySelector('#studentImportDialog').close();
  const styles=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8');
  assert.match(styles,/\.student-code-note\{color:var\(--blue\);font-size:12px;font-weight:700\}/);
  assert.ok(styles.lastIndexOf('.invoice-page .issuer{left:520px')>styles.lastIndexOf('.invoice-page .issuer{left:555px'));
  assert.ok(styles.includes('.invoice-page .totals{top:calc(535px + var(--detail-count) * 28px)}'));
  assert.match(styles,/\.invoice-page \.bank-box\{[\s\S]*?min-height:92px;[\s\S]*?max-height:92px;/);
  assert.match(styles,/\.invoice-page \.section-box\{[\s\S]*?white-space:pre-wrap;[\s\S]*?overflow-wrap:anywhere;/);
  assert.match(styles,/@media\(min-width:851px\)\{[\s\S]*?\.invoice-list-pane\{display:flex;flex-direction:column\}[\s\S]*?\.invoice-list\{flex:0 1 auto;min-height:0;max-height:960px;overflow:auto\}/);
  assert.match(styles,/\.invoice-list-statuses \.status,\.invoice-list-statuses \.payment-pill\{padding:2px 6px;font-size:10px\}/);
  assert.match(appSource,/emailOpenedAt\?'<span class="status accessed">開封<\/span>'/);
  assert.match(appSource,/URL確認/);
  assert.match(styles,/\.invoice-detail-fields\{display:flex;align-items:center;flex:1 0 100%;flex-wrap:wrap;[^}]*margin:0/);
  assert.match(styles,/\.invoice-detail-actions\{align-items:center;flex-direction:row;margin-top:10px/);
  assert.match(styles,/\.invoice-detail-actions \.button,\.invoice-detail-actions summary\.button\{[^}]*height:38px;[^}]*white-space:nowrap\}/);
  assert.match(styles,/\.invoice-list-statuses \.payment-pill\.paid\{font-size:11px\}/);
  assert.match(styles,/\.pdf-render-host\{[^}]*height:auto;[^}]*overflow:visible/);
  assert.match(styles,/\.invoice-inline-preview:has\(\.invoice-page\+\.invoice-page\)::before\{content:'複数ページあります/);
  assert.match(styles,/\.invoice-inline-preview \.invoice-page\+\.invoice-page\{margin-top:28px\}/);
  console.log('ui tests passed');
}

main().catch(error=>{console.error(error);process.exitCode=1;});
