const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {JSDOM} = require('jsdom');

const root = path.resolve(__dirname, '..');
const dom = new JSDOM(fs.readFileSync(path.join(root, 'index.html'), 'utf8'), {
  url: 'https://stepkobetsu-hub.github.io/invoice-pdf/#partners',
  runScripts: 'outside-only'
});
const {window} = dom;
window.localStorage.setItem('stepStaffAppAuth',JSON.stringify({systemPortalSessionToken:'test-staff-session'}));
let submittedStaffToken='';
window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
window.HTMLDialogElement.prototype.close=function(){this.open=false;};
window.HTMLFormElement.prototype.submit=function(){
  const value=name=>this.querySelector(`[name="${name}"]`)?.value||'';
  const requestId=value('requestId'),bridgeNonce=value('bridgeNonce'),action=value('action');
  submittedStaffToken=value('systemPortalSessionToken');
  if(!requestId)return;
  const data=action==='getDashboard'?{invoices:[],history:[]}:{count:1};
  window.setTimeout(()=>window.dispatchEvent(new window.MessageEvent('message',{origin:'https://script.google.com',data:{requestId,bridgeNonce,result:{ok:true,data}}})),0);
};
window.print=()=>{};
window.fetch=async()=>({ok:true,json:async()=>({status:200,results:[{address1:'愛知県',address2:'春日井市',address3:'大留町'}]})});
window.eval(fs.readFileSync(path.join(root, 'assets/core.js'), 'utf8'));
window.eval(fs.readFileSync(path.join(root, 'assets/invoice-pdf.js'), 'utf8'));
window.eval(fs.readFileSync(path.join(root, 'assets/app.js'), 'utf8'));

async function main(){
  const document=window.document;
  assert.equal(document.querySelector('#view-partners').classList.contains('active'),true);
  document.querySelector('[data-view="create"]').click();
  assert.equal(window.location.hash,'#create');
  document.querySelector('[data-create-method="single"]').click();
  await new Promise(resolve=>window.setTimeout(resolve,0));
  assert.equal(submittedStaffToken,'test-staff-session');
  assert.equal(document.querySelector('#createSinglePane').classList.contains('active'),true);
  assert.match(document.querySelector('[name="invoiceNumber"]').value,/^\d{9}$/);
  assert.equal(document.querySelector('[name="invoiceNumber"]').readOnly,true);
  const invoiceDate=document.querySelector('[name="invoiceDate"]').value;
  const dueDate=document.querySelector('[name="dueDate"]').value;
  assert.equal((new Date(`${dueDate}T00:00:00`)-new Date(`${invoiceDate}T00:00:00`))/86400000,21);
  document.querySelector('#previewSingleInvoice').click();
  assert.equal(document.querySelector('#previewDialog').open,false);
  assert.match(document.querySelector('#globalAlert').textContent,/取引先/);
  assert.match(document.querySelector('#globalAlert').textContent,/明細1の品目/);
  assert.match(document.querySelector('#globalAlert').textContent,/明細1の単価/);
  assert.equal(document.querySelector('#singlePartner').classList.contains('field-missing'),true);
  const saveButton=document.querySelector('#singleInvoiceForm button[type="submit"]');
  assert.equal(saveButton.textContent,'保存して発行リストへ追加');
  assert.ok(document.querySelector('#previewSingleInvoice').compareDocumentPosition(saveButton)&window.Node.DOCUMENT_POSITION_FOLLOWING);
  assert.equal(document.querySelector('#confirmPdf'),null);

  document.querySelector('#loadDemoPartners').click();
  await new Promise(resolve=>window.setTimeout(resolve,0));
  assert.equal(document.querySelectorAll('#partnerTable tbody tr').length,4);
  assert.equal(document.querySelectorAll('#singlePartner option').length,5);
  assert.match(document.querySelector('#partnerTable').textContent,/mintcocoajasmine@gmail\.com/);
  assert.match(document.querySelector('#partnerTable').textContent,/kk8989892000@yahoo\.co\.jp/);
  assert.match(document.querySelector('#partnerTable').textContent,/skase\.days@gmail\.com/);
  assert.match(document.querySelector('#partnerTable').textContent,/chloeandnina1@gmail\.com/);

  const form=document.querySelector('#singleInvoiceForm');
  form.elements.partnerCode.value='DEMO001';
  form.elements.invoiceNumber.value='202608501';
  form.elements.subject.value='2026年8月分';
  form.elements.invoiceDate.value='2026-08-09';
  form.elements.dueDate.value='2026-08-31';
  document.querySelector('[name="detailName"]').value='授業料';
  document.querySelector('[name="detailUnitPrice"]').value='25000';
  document.querySelector('[name="detailQuantity"]').value='1';
  document.querySelector('[name="detailUnitPrice"]').dispatchEvent(new window.Event('input',{bubbles:true}));
  assert.equal(document.querySelector('#singleTotal').textContent,'27,500円');
  document.querySelector('#previewSingleInvoice').click();
  assert.equal(document.querySelector('#previewDialog').open,true);
  assert.equal(document.querySelectorAll('#previewDialog #printPreview').length,1);
  assert.equal(document.querySelectorAll('#previewDialog #downloadPreview').length,1);
  assert.equal(document.querySelector('#printPreview').textContent,'プレビューを印刷');
  assert.equal(document.querySelector('#downloadPreview').textContent,'プレビューPDFを保存');
  assert.match(document.querySelector('#invoicePage').textContent,/プレビュー/);
  assert.equal(document.querySelector('#invoicePage .preview-watermark').textContent,'プレビュー');
  assert.match(document.querySelector('#invoicePage').getAttribute('style'),/--detail-count:1/);
  const twoLineHtml=window.StepInvoicePdf.pageHtml({...window.StepInvoiceCore.buildManualInvoice({invoiceNumber:'202608999',subject:'2026年8月分',invoiceDate:'2026-08-09',dueDate:'2026-08-30'},[{name:'授業料',unitPrice:25000,quantity:1,taxRate:10},{name:'分譲経費',unitPrice:2500,quantity:1,taxRate:10}],window.StepInvoiceCore.DEMO_PARTNERS[0])});
  assert.match(twoLineHtml,/--detail-count:2/);
  assert.match(twoLineHtml,/愛知県春日井市大留町1丁目23-2/);
  assert.doesNotMatch(twoLineHtml,/preview-watermark/);
  assert.match(window.StepInvoicePdf.pageHtml(window.StepInvoiceCore.buildManualInvoice({invoiceNumber:'202608998',subject:'2026年8月分',invoiceDate:'2026-08-09',dueDate:'2026-08-30'},[{name:'授業料',unitPrice:7000,quantity:1,taxRate:10}],window.StepInvoiceCore.DEMO_PARTNERS[0]),{preview:true}),/preview-watermark/);
  document.querySelector('#previewDialog').close();
  form.dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));
  await new Promise(resolve=>window.setTimeout(resolve,20));
  assert.match(document.querySelector('#createTable tbody').textContent,/202608501/);
  assert.match(document.querySelector('#createTable tbody').textContent,/ダミー取引先1/);

  document.querySelector('#openPartnerForm').click();
  const partnerForm=document.querySelector('#partnerForm');
  partnerForm.elements.customerCode.value='NEW001';
  partnerForm.elements.name.value='個別入力テスト';
  partnerForm.elements.email.value='new@example.com';
  partnerForm.dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));
  assert.match(document.querySelector('#partnerTable').textContent,/個別入力テスト/);
  assert.match(document.querySelector('#singlePartner').textContent,/NEW001/);
  document.querySelector('[data-edit-partner="NEW001"]').click();
  assert.equal(document.querySelector('#partnerDialogTitle').textContent,'取引先を編集');
  assert.equal(partnerForm.elements.customerCode.readOnly,true);
  partnerForm.elements.name.value='個別入力テスト（編集済）';
  partnerForm.dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));
  assert.match(document.querySelector('#partnerTable').textContent,/個別入力テスト（編集済）/);
  assert.equal(document.querySelector('#partnerDialog #deletePartnerButton'),null);
  document.querySelector('[data-delete-partner="NEW001"]').click();
  assert.equal(document.querySelector('#deletePartnerDialog').open,true);
  assert.equal(document.querySelector('#confirmDeletePartner').disabled,true);
  document.querySelector('#deletePartnerCodeInput').value='NEW001';
  document.querySelector('#deletePartnerCodeInput').dispatchEvent(new window.Event('input',{bubbles:true}));
  document.querySelector('#deletePartnerCheck').checked=true;
  document.querySelector('#deletePartnerCheck').dispatchEvent(new window.Event('change',{bubbles:true}));
  assert.equal(document.querySelector('#confirmDeletePartner').disabled,false);
  document.querySelector('#confirmDeletePartner').click();
  await new Promise(resolve=>window.setTimeout(resolve,0));
  assert.doesNotMatch(document.querySelector('#partnerTable').textContent,/個別入力テスト（編集済）/);

  document.querySelector('#openPartnerForm').click();
  partnerForm.elements.postal.value='4870024';
  partnerForm.elements.postal.dispatchEvent(new window.Event('change',{bubbles:true}));
  await new Promise(resolve=>window.setTimeout(resolve,0));
  assert.equal(partnerForm.elements.postal.value,'487-0024');
  assert.equal(partnerForm.elements.prefecture.value,'愛知県');
  assert.equal(partnerForm.elements.address1.value,'春日井市大留町');
  document.querySelector('#partnerDialog').close();

  document.querySelector('#openStudentImport').click();
  assert.equal(document.querySelector('#studentImportDialog').open,true);
  assert.match(document.querySelector('#studentImportDialog').textContent,/生徒コード/);
  assert.match(document.querySelector('#studentImportDialog').textContent,/※半角英数で入力してください。/);
  assert.equal(document.querySelector('#studentSearchForm [name="studentCode"]').pattern,'[A-Za-z0-9]+');
  assert.match(document.querySelector('#settingsForm [name="apiUrl"]').value,/^https:\/\/script\.google\.com\/macros\/s\//);
  const backend=fs.readFileSync(path.join(root,'apps-script/Code.gs'),'utf8');
  assert.match(backend,/action:'verifySystemPortal'/);
  assert.match(backend,/AUTH_PERMISSION_LEVELS:\['2','3','4'\]/);
  assert.match(backend,/AUTH_PERMISSION_LEVELS\.includes\(String\(result\.permissionLevel\)\)/);
  assert.match(backend,/processPendingSends: \(\) => processPendingSends_\(requestAuth\)/);
  assert.match(backend,/installQueueTrigger_\(\);\s*return response/);
  assert.doesNotMatch(backend,/if\(payload\.preflight!==true\)processSendQueue\(\)/);
  document.querySelector('#studentImportDialog').close();
  const styles=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8');
  assert.ok(styles.lastIndexOf('.invoice-page .issuer{left:520px')>styles.lastIndexOf('.invoice-page .issuer{left:555px'));
  assert.ok(styles.includes('.invoice-page .totals{top:calc(535px + var(--detail-count) * 34px)}'));
  console.log('ui tests passed');
}

main().catch(error=>{console.error(error);process.exitCode=1;});
